#!/usr/bin/env bash

# +-----+
# | zsh |
# +-----+

alias d='dirs -v'
for index ({1..9}) alias "$index"="cd +${index}"; unset index

# +----+
# | ls |
# +----+

alias ll='ls -lah'

# +-----+
# | git |
# +-----+

alias gs='git status'
alias ga='git add'
alias gc='git commit'
alias gp='git push'
