#!/usr/bin/env bash

# +-----+
# | zsh |
# +-----+

alias d='dirs -v'
for index ({1..9}) alias "$index"="cd +${index}"; unset index

# +----+
# | ls |
# +----+

alias ll='ls -lah'

# +-----+
# | git |
# +-----+

alias gs='git status'
alias ga='git add'
alias gc='git commit'
alias gp='git push'
alias gpl='git pull'
alias gsw='git switch'
alias gst='git stack'
alias gstp='git stack --push'
alias gsy='git sync'

# +-----+
# | cog |
# +-----+

alias cogci='cog commit'
