# For dotfiles
export XDG_CONFIG_HOME="$HOME/.config"

# For specific data
export XDG_DATA_HOME="$HOME/.local/share"

# For cached files
export XDG_CACHE_HOME="$HOME/.cache"

# editor
export EDITOR="nvim"
export VISUAL="nvim"

# zsh
export ZDOTDIR="$XDG_CONFIG_HOME/zsh"

# History filepath
export HISTFILE="$ZDOTDIR/.zhistory"
# Maximum events for internal history
export HISTSIZE=10000
# Maximum events in history file
export SAVEHIST=10000

# other software
export VIMCONFIG="$XDG_CONFIG_HOME/nvim"

export DOTFILES="$HOME/.dotfiles"

# PATH
export PATH="$HOME/.local/bin:$PATH"
export PATH="$HOME/.cargo/bin:$PATH"
export PATH="$HOME/.yarn/bin:$PATH"         # YARN
export PATH="$HOME/.qlty/bin:$PATH"         # qlty

# fzf
export FZF_DEFAULT_COMMAND="rg --files --hidden --glob '!.git'" 
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"

# uv
export UV_GIT_LFS=1
