#!/usr/bin/env zsh

# +------------+
# | NAVIGATION |
# +------------+

setopt AUTO_CD              # Go to folder path without using cd.

setopt AUTO_PUSHD           # Push the old directory onto the stack on cd.
setopt PUSHD_IGNORE_DUPS    # Do not store duplicates in the stack.
setopt PUSHD_SILENT         # Do not print the directory stack after pushd or popd.

# +---------+
# | Aliases |
# +---------+
#
source "$XDG_CONFIG_HOME/zsh/aliases"

# +--------+
# | Prompt |
# +--------+

fpath=($DOTFILES/zsh/prompt $fpath)
source $DOTFILES/zsh/prompt/prompt_purification_setup

# +------------+
# | Completion |
# +------------+
fpath=($ZDOTDIR/external $fpath)
autoload -U compinit; compinit

# Autocomplete hidden files
_comp_options+=(globdots)
source "$DOTFILES/zsh/external/completion.zsh"
