#!/usr/bin/env zsh

# +------------+
# | NAVIGATION |
# +------------+

setopt AUTO_CD              # Go to folder path without using cd.

setopt AUTO_PUSHD           # Push the old directory onto the stack on cd.
setopt PUSHD_IGNORE_DUPS    # Do not store duplicates in the stack.
setopt PUSHD_SILENT         # Do not print the directory stack after pushd or popd.

setopt AUTO_PARAM_SLASH
unsetopt CASE_GLOB

source "$DOTFILES/zsh/external/bd.zsh"

# +---------+
# | History |
# +---------+

setopt EXTENDED_HISTORY          # Write the history file in the ':start:elapsed;command' format.
setopt SHARE_HISTORY             # Share history between all sessions.
setopt HIST_EXPIRE_DUPS_FIRST    # Expire a duplicate event first when trimming history.
setopt HIST_IGNORE_DUPS          # Do not record an event that was just recorded again.
setopt HIST_IGNORE_ALL_DUPS      # Delete an old recorded event if a new event is a duplicate.
setopt HIST_FIND_NO_DUPS         # Do not display a previously found event.
setopt HIST_IGNORE_SPACE         # Do not record an event starting with a space.
setopt HIST_SAVE_NO_DUPS         # Do not write a duplicate event to the history file.
setopt HIST_VERIFY               # Do not execute immediately upon history expansion.

# +---------+
# | Aliases |
# +---------+
#
source "$XDG_CONFIG_HOME/zsh/aliases"


# +---------+
# | SCRIPTS |
# +---------+

source "$DOTFILES/zsh/scripts.zsh"

# +--------+
# | Prompt |
# +--------+

#fpath=($DOTFILES/zsh/prompt $fpath)
#source $DOTFILES/zsh/prompt/prompt_purification_setup
eval "$(starship init zsh)"


# +-----------+
# | VI KEYMAP |
# +-----------+

# Vi mode
bindkey -v
export KEYTIMEOUT=1

# change cursor
source "$DOTFILES/zsh/plugins/cursor_mode"

zmodload zsh/complist
bindkey -M menuselect 'h' vi-backward-char
bindkey -M menuselect 'k' vi-up-line-or-history
bindkey -M menuselect 'l' vi-forward-char
bindkey -M menuselect 'j' vi-down-line-or-history

autoload -Uz edit-command-line
zle -N edit-command-line
bindkey -M vicmd v edit-command-line

# +------------+
# | Completion |
# +------------+

fpath=($ZDOTDIR/external $fpath)
autoload -U compinit; compinit

# Autocomplete hidden files
_comp_options+=(globdots)
source "$DOTFILES/zsh/external/completion.zsh"

#
# FZF
#

if [ $(command -v "fzf") ];
then
    if [ -e /usr/share/fzf/completion.zsh ]; 
    then
        source /usr/share/fzf/completion.zsh
        source /usr/share/fzf/key-bindings.zsh
    else
        source /data/data/com.termux/files/usr/share/fzf/completion.zsh
        source /data/data/com.termux/files/usr/share/fzf/key-bindings.zsh
    fi
fi

# Load custom rc if present

if [ -e "$ZDOTDIR/.zshrc-local" ]; then
    source "$ZDOTDIR/.zshrc-local"
fi

#
# direnv
#

if [ $(command -v "direnv") ];
then
    eval "$(direnv hook zsh)"
fi
